

	CREATE OR REPLACE VIEW V_PBI_FAT_VEICULOS
	AS

	SELECT
	    (FMV.EMPRESA || ' - ' || FMV.VEICULO) AS CHAVE_VEICULO,
		(FMC.EMPRESA || ' - ' || FMC.REVENDA) AS CHAVE_EMP_REV,
		(FMC.EMPRESA || ' - ' || FMC.REVENDA || ' - ' || FMC.CONTATO) AS CHAVE_EMP_REV_CONTATO,
		 
		 -- FMC TRAS TODAS AS COLUNAS DA TABELA FAT_MOVIMENTO_CAPA
		 FMC.*,
		 -- FMV TRAZ TODAS AS COLUNAS DA TABELA FAT_MOVIMENTO_VEICULO
		  FMV.VEICULO        AS VEICULO_FATURAMENTO  ,
		  FMV.VAL_TOTAL                               ,
		  FMV.VAL_CUSTO                               ,
		  FMV.VAL_OPCIONAIS                           ,
		  FMV.VAL_DESCONTO                            ,
		  FMV.VAL_FRETE                               ,
		  FMV.VAL_DEVERIA
		
	FROM CNP.FAT_MOVIMENTO_CAPA FMC
	
	-- JOIN COM A TABELA FAT_MOVIMENTO_VEICULOS

	INNER JOIN CNP.FAT_MOVIMENTO_VEICULO FMV 
	    ON FMV.EMPRESA = FMC.EMPRESA
		AND FMV.REVENDA = FMC.REVENDA
		AND FMV.NUMERO_NOTA_FISCAL = FMC.NUMERO_NOTA_FISCAL
		AND FMV.SERIE_NOTA_FISCAL = FMC.SERIE_NOTA_FISCAL
		AND FMV.TIPO_TRANSACAO = FMC.TIPO_TRANSACAO
		AND FMV.CONTADOR = FMC.CONTADOR
		
	-- JOIN COM A TABELA VEICULOS	
	INNER JOIN CNP.VEI_VEICULO VEI 
	ON VEI.EMPRESA = FMV.EMPRESA
		AND VEI.VEICULO = FMV.VEICULO
		
	-- JOIN COM A TABELA USUARIOS	
	INNER JOIN CNP.GER_USUARIO USU 
	ON USU.USUARIO = FMC.USUARIO

	-- JOIN COM A TABELA TIPO DE TRANSAÇÃO
	INNER JOIN CNP.FAT_TIPO_TRANSACAO FTT 
	ON FTT.TIPO_TRANSACAO = FMC.TIPO_TRANSACAO
	
	-- FILTROS	/ TRANSAÇÃO / ULTIMOS 5 ANOS / STATUS FECHADO
	WHERE 1 = 1 
		AND FMC.TIPO_TRANSACAO IN ('V21','U21') 
		AND EXTRACT(YEAR FROM FMC.DTA_ENTRADA_SAIDA) > 2020 
		AND FMC.STATUS = 'F'




CREATE OR REPLACE VIEW V_PBI_FAT_VEICULOS
AS
SELECT
    (FMV.EMPRESA || ' - ' || FMV.VEICULO) AS CHAVE_VEICULO,
    (FMC.EMPRESA || ' - ' || FMC.REVENDA) AS CHAVE_EMP_REV,
    (FMC.EMPRESA || ' - ' || FMC.REVENDA || ' - ' || FMC.CONTATO) AS CHAVE_EMP_REV_CONTATO,

    -- FMC TRAS TODAS AS COLUNAS DA TABELA FAT_MOVIMENTO_CAPA
    FMC.*,

    -- FMV TRAZ TODAS AS COLUNAS DA TABELA FAT_MOVIMENTO_VEICULO
    FMV.*

FROM CNP.FAT_MOVIMENTO_CAPA FMC

	-- JOIN COM A TABELA FAT_MOVIMENTO_VEICULOS

INNER JOIN CNP.FAT_MOVIMENTO_VEICULO FMV 
    ON FMV.EMPRESA = FMC.EMPRESA
    AND FMV.REVENDA = FMC.REVENDA
    AND FMV.NUMERO_NOTA_FISCAL = FMC.NUMERO_NOTA_FISCAL
    AND FMV.SERIE_NOTA_FISCAL = FMC.SERIE_NOTA_FISCAL
    AND FMV.TIPO_TRANSACAO = FMC.TIPO_TRANSACAO
    AND FMV.CONTADOR = FMC.CONTADOR

	-- JOIN COM A TABELA VEICULOS	

INNER JOIN CNP.VEI_VEICULO VEI 
    ON VEI.EMPRESA = FMV.EMPRESA
    AND VEI.VEICULO = FMV.VEICULO

	-- JOIN COM A TABELA USUARIOS	

INNER JOIN CNP.GER_USUARIO USU 
    ON USU.USUARIO = FMC.USUARIO

	-- JOIN COM A TABELA TIPO DE TRANSAÇÃO

INNER JOIN CNP.FAT_TIPO_TRANSACAO FTT 
    ON FTT.TIPO_TRANSACAO = FMC.TIPO_TRANSACAO

	-- FILTROS	/ TRANSAÇÃO / ULTIMOS 5 ANOS / STATUS FECHADO

WHERE FMC.TIPO_TRANSACAO IN ('V21','U21')
  AND EXTRACT(YEAR FROM FMC.DTA_ENTRADA_SAIDA) > 2020
  AND FMC.STATUS = 'F';


