	CREATE OR REPLACE VIEW V_PBI_PAINEL_VENDAS AS
	SELECT
		/* ================= CONTATO ================= */
		CC.EMPRESA,
		CC.REVENDA,
		(TO_CHAR(CC.EMPRESA) || ' - ' || TO_CHAR(CC.REVENDA)) AS CHAVE_EMP_REV,
		CC.CONTATO,
		CC.DTA_CONTATO,
		CC.DES_CONTATO,
		CC.DTA_NOVO_CONTATO,

		CAST(
			CASE
				WHEN CC.SITUACAO = 'A' THEN 'ABERTO'
				WHEN CC.SITUACAO = 'F' THEN 'FECHADO'
			ELSE TO_CHAR(CC.SITUACAO)
		END
		AS VARCHAR (30)) AS SITUACAO,

		CAST(
			CASE
				WHEN CC.DEPARTAMENTO = 1 THEN 'VEICULO NOVO'
				WHEN CC.DEPARTAMENTO = 2 THEN 'VEICULO USADO'
			ELSE TO_CHAR(CC.DEPARTAMENTO)
		END
		AS VARCHAR2(30)) AS DEPARTAMENTO,


		CC.FORMA_CONTATO AS FORMA_CONTATO_NOVO,

		/* ================= RESGATE ================= */
		CASE
			WHEN CC.RESGATE = 'S'
			 AND CC.CONTATO_ORIGEM IS NOT NULL
			THEN CC.CONTATO_ORIGEM
			ELSE 0
		END AS NRO_CONTATO_ORIGEM,

	   /* ================= ÚLTIMO CONTATO ================= */
	   (
		SELECT MAX(C2.DTA_CONTATO)
		FROM CNP.CAC_CONTATO C2
		WHERE C2.EMPRESA = CC.EMPRESA
		  AND C2.REVENDA = CC.REVENDA
		  AND C2.CLIENTE = CC.CLIENTE
		  AND C2.CONTATO < CC.CONTATO
		  AND C2.DTA_CONTATO >= ADD_MONTHS(TRUNC(SYSDATE), -60)
		  AND C2.DTA_CONTATO <= TRUNC(SYSDATE)
		  ) AS DTA_ULTIMO_CONTATO,

		/* ================= ORIGEM DO TRAFEGO ================= */
		(
			SELECT COT.DES_ORIGEM_TRAFEGO
			FROM CNP.CAC_ORIGEM_TRAFEGO COT
			WHERE COT.EMPRESA = CC.EMPRESA
			  AND COT.ORIGEM_TRAFEGO = CC.ORIGEM_TRAFEGO
		) DES_ORIGEM_TRAFEGO,
		
		/* ================= USUÁRIOS ================= */
		GU.LOGIN       AS NOME_USUARIO,
		GU_ABRIU.LOGIN AS USUARIO_ABRIU,

		/* ================= CLIENTE ================= */
		FC.CLIENTE,
		FC.NOME AS NOME_CLIENTE,
		FC.DDD_CELULAR,
		FC.CELULAR,
		FC.DDD_TELEFONE,
		FC.TELEFONE,

		CASE
			WHEN FC.DDD_CELULAR > 99
			THEN CAST(FC.DDD_CELULAR AS CHAR(3)) || CAST(FC.CELULAR AS CHAR(10))
			ELSE CAST(FC.DDD_CELULAR AS CHAR(2)) || CAST(FC.CELULAR AS CHAR(10))
		END AS CLI_CELULAR,

		CASE
			WHEN FC.DDD_TELEFONE > 99
			THEN CAST(FC.DDD_TELEFONE AS CHAR(3)) || CAST(FC.TELEFONE AS CHAR(10))
			ELSE CAST(FC.DDD_TELEFONE AS CHAR(2)) || CAST(FC.TELEFONE AS CHAR(10))
		END AS CLI_TELEFONE,

	/* ================= PROPOSTA ================= */

	  CASE
		WHEN VP.PROPOSTA IS NOT NULL THEN VP.PROPOSTA
		ELSE (
			SELECT MAX(VAE.PROPOSTA)
			FROM CNP.VEI_AGENDA_ENTREGA VAE
			WHERE VAE.EMPRESA = CC.EMPRESA
			  AND VAE.REVENDA = CC.REVENDA
			  AND TRUNC(VAE.DTA_ENTREGA_PREVISTA) = TRUNC(CC.DTA_CONTATO)
			  AND CC.CONTATO_ORIGEM = (
					SELECT MAX(VP2.CONTATO)
					FROM CNP.VEI_PROPOSTA VP2
					WHERE VP2.EMPRESA = VAE.EMPRESA
					  AND VP2.REVENDA = VAE.REVENDA
					  AND VP2.VEICULO = VAE.VEICULO
			  )
		)
	  END AS PROPOSTA,

		/* ================= FORMA CONTATO ================= */
		CFC.DES_FORMA_CONTATO,

		/* ================= INTERESSE (AGREGADO) ================= */
		CI.MODELO_INTERESSE,
		CI.ANO_MODELO_INTERESSE,
		VMI.FAMILIA,
		VMI.DES_MODELO AS DES_MODELO_INTERESSE,
		CI.MAIOR_POSSIBILIDADE_FECHAR,
		CI.DTA_FECHAMENTO_VENDA,

		/* ================= STATUS ================= */
		ST.DES_STATUS_CONTATO,
		TC.DES_TIPO_CONTATO,
		STC.DES_SUB_TIPO_CONTATO,

		/* ================= PROVIDÊNCIA ================= */
		CP.COD_PROVIDENCIA,
		CP.DTA_PROVIDENCIA,
		CP.DES_PROVIDENCIA,
		CP.USUARIO_ENCAMINHADO,
		CP.TIPO_PROVIDENCIA,

		/* ================= INDICADORES ================= */
		CAST(
		CASE
		  WHEN CC.DTA_CONTATO IS NOT NULL
		  THEN TRUNC(SYSDATE) - TRUNC(CC.DTA_CONTATO)
		  ELSE 0
		END
	  AS NUMBER) AS NRO_DIAS


	FROM CNP.CAC_CONTATO CC

	/* ================= CLIENTE ================= */
	INNER JOIN CNP.FAT_CLIENTE FC
			ON FC.CLIENTE = CC.CLIENTE

	/* ================= USUÁRIOS ================= */
	INNER JOIN CNP.GER_USUARIO GU
			ON GU.USUARIO = CC.USUARIO_ENCAMINHADO

	LEFT JOIN CNP.GER_USUARIO GU_ABRIU
		   ON GU_ABRIU.USUARIO = CC.USUARIO_ABRIU

	/* ================= FORMA CONTATO ================= */
	INNER JOIN CNP.CAC_FORMA_CONTATO CFC
			ON CFC.EMPRESA = CC.EMPRESA
		   AND CFC.FORMA_CONTATO = CC.FORMA_CONTATO

	/* ================= CAMPANHA ================= */
	LEFT JOIN CNP.CAC_CAMPANHA CAM
		   ON CAM.EMPRESA = CC.EMPRESA
		  AND CAM.CAMPANHA = CC.CAMPANHA
		  AND CAM.DESTINO IN ('A','T')

	/* ================= PROPOSTA ================= */
	LEFT JOIN CNP.VEI_PROPOSTA VP
		   ON VP.EMPRESA = CC.EMPRESA
		  AND VP.REVENDA = CC.REVENDA
		  AND VP.CONTATO = CC.CONTATO

	/* ================= INTERESSE (OTIMIZADO) ================= */
	LEFT JOIN (
		SELECT
			CI.EMPRESA,
			CI.REVENDA,
			CI.CONTATO,
			MAX(CI.MODELO) AS MODELO_INTERESSE,
			MAX(CI.ANO) AS ANO_MODELO_INTERESSE,
			CAST(MIN(CI.DTA_TESTE_DRIVE) AS DATE) AS DTA_TESTE_DRIVE,
		CAST(MIN(CI.DTA_TEST_DRIVE_REA) AS DATE) AS DTA_TEST_DRIVE_REA,
		CAST(MIN(CI.DTA_FECHAMENTO) AS DATE) AS DTA_FECHAMENTO_VENDA,

			CASE
				WHEN MAX(CI.POSSIBILIDADE_FECHAR) = 0 THEN 'Frio'
				WHEN MAX(CI.POSSIBILIDADE_FECHAR) = 1 THEN 'Morno'
				WHEN MAX(CI.POSSIBILIDADE_FECHAR) = 2 THEN 'Quente'
				WHEN MAX(CI.POSSIBILIDADE_FECHAR) = 3 THEN 'Super-Quente'
			END AS MAIOR_POSSIBILIDADE_FECHAR
		FROM CNP.CAC_INTERESSE CI
		GROUP BY
			CI.EMPRESA,
			CI.REVENDA,
			CI.CONTATO
	) CI
	ON CI.EMPRESA = CC.EMPRESA
	AND CI.REVENDA = CC.REVENDA
	AND CI.CONTATO = CC.CONTATO

	/* ================= MODELO VEÍCULO ================= */
	LEFT JOIN CNP.VEI_MODELO VMI
		   ON VMI.EMPRESA = CC.EMPRESA
		  AND VMI.MODELO  = CI.MODELO_INTERESSE

	/* ================= DOMÍNIOS ================= */
	LEFT JOIN CNP.CAC_STATUS_CONTATO ST
		   ON ST.EMPRESA = CC.EMPRESA
		  AND ST.STATUS_CONTATO = CC.STATUS_CONTATO

	LEFT JOIN CNP.CAC_CANAL_ACESSO CAN
		   ON CAN.EMPRESA = CC.EMPRESA
		  AND CAN.CANAL_ACESSO = CC.CANAL_ACESSO

	LEFT JOIN CNP.CAC_TIPO_TRAFEGO TT
		   ON TT.EMPRESA = CC.EMPRESA
		  AND TT.TIPO_TRAFEGO = CC.TIPO_TRAFEGO

	LEFT JOIN CNP.CAC_TIPO_CONTATO TC
		   ON TC.EMPRESA = CC.EMPRESA
		  AND TC.TIPO_CONTATO = CC.TIPO_CONTATO

	LEFT JOIN CNP.CAC_SUB_TIPO_CONTATO STC
		   ON STC.EMPRESA = CC.EMPRESA
		  AND STC.TIPO_CONTATO = CC.TIPO_CONTATO
		  AND STC.SUB_TIPO_CONTATO = CC.SUB_TIPO_CONTATO

	/* ================= PROVIDÊNCIA ================= */
		LEFT JOIN (
			SELECT
				CP.EMPRESA,
				CP.REVENDA,
				CP.CONTATO,
				CP.PROVIDENCIA        AS COD_PROVIDENCIA,
				CP.DTA_PROVIDENCIA,
				CP.DES_PROVIDENCIA,
				CP.USUARIO_ENCAMINHADO,
				CP.TIPO_PROVIDENCIA,
				ROW_NUMBER() OVER (
					PARTITION BY CP.EMPRESA, CP.REVENDA, CP.CONTATO
					ORDER BY CP.DTA_PROVIDENCIA DESC, CP.PROVIDENCIA DESC
				) AS RN
			FROM CNP.CAC_PROVIDENCIA CP
		) CP
		ON CP.EMPRESA = CC.EMPRESA
		AND CP.REVENDA = CC.REVENDA
		AND CP.CONTATO = CC.CONTATO
		AND CP.RN = 1


	/* ================= FILTROS ================= */
	WHERE CC.EMPRESA IN (1,2,3)
	  AND CC.REVENDA IN (1,2)
	 -- AND CC.DEPARTAMENTO IN (1,2)
	  AND CC.SITUACAO IN ('A','F')
	  AND CC.ORIGEM   = 'V'
	  AND CC.DTA_CONTATO >= ADD_MONTHS(TRUNC(SYSDATE), -60)
	  AND NVL(GU.LOGIN, '##SEM_LOGIN##') NOT IN
		  ('ADMIN','DANILO','PPRATES','EBRITO','LOIZEANE','MONALISA','RBENTO','REJANE','LIZIANE','FCRUZ','ELOISA','MCSILVA')
	  AND EXISTS (
			SELECT 1
			FROM CNP.FAT_VENDEDOR FV
			WHERE FV.EMPRESA = CC.EMPRESA
			  AND FV.REVENDA = CC.REVENDA
			  AND FV.USUARIO = CC.USUARIO_ENCAMINHADO
			  AND FV.FUNCAO = 'V'
			  AND FV.ATIVO = 'S'
			  AND FV.INATIVO_CONSULTAS = 'N'
	  );
