
SELECT
    -- ========== IDENTIFICAÇÃO DA EMPRESA E REVENDA ==========
    V.EMPRESA,
    V.REVENDA_ORIGEM,
    TO_CHAR(V.EMPRESA) || ' - ' || TO_CHAR(V.REVENDA_ORIGEM)  AS CHAVE_EMP_REV,
    TO_CHAR(V.EMPRESA) || ' - ' || TO_CHAR(V.VEICULO)         AS CHAVE_VEICULO,
    TO_CHAR(V.EMPRESA) || ' - ' || TO_CHAR(V.CHASSI)          AS CHAVE_EMP_CHASSI,
    V.REVENDA_NFENTRADA,
    GR.NOME_FANTASIA AS EMPRESA_REVENDA,
    -- ========== SITUAÇÃO E RESERVA ==========
    VS.DES_SITUACAO                AS SITUACAO,
    TRUNC(V.DTA_RESERVA)          AS DTA_RESERVA,      -- ✅ TRUNC aplicado
    TRUNC(V.DTA_FIM_RESERVA)      AS DTA_FIM_RESERVA,  -- ✅ TRUNC aplicado
    V.RESERVADO,
    -- ========== DADOS DO VEÍCULO ==========
    V.VEICULO,
    V.CHASSI,
    V.COR,
    V.MODELO,
    VF.MARCA,
    VF.DES_FAMILIA,
    VM.DES_MODELO,
    VM.PRECO_PUBLICO,
    V.QUILOMETRAGEM,
    -- ========== CLASSIFICAÇÃO NOVO/USADO ==========
    CASE
        WHEN V.NOVO_USADO = 'U' THEN 'USADOS'
        WHEN V.NOVO_USADO = 'N' THEN 'NOVOS'
        ELSE 'NÃO CLASSIFICADO'
    END AS NOVO_USADO,
    -- ========== CONTROLE DE ESTOQUE ==========
    TRUNC(V.DTA_ENTRADA)                                AS DTA_ENTRADA,  -- ✅ TRUNC aplicado
    (TRUNC(SYSDATE) - TRUNC(V.DTA_ENTRADA))             AS DIAS_ESTOQUE,
    -- ========== CLASSIFICAÇÃO POR DIAS EM ESTOQUE ==========
    -- ✅ Corrigido: gap entre 60-61 e 120-121 estava descoberto (> e <, sem =)
    CASE
        WHEN (TRUNC(SYSDATE) - TRUNC(V.DTA_ENTRADA)) <= 60  THEN '0-60'
        WHEN (TRUNC(SYSDATE) - TRUNC(V.DTA_ENTRADA)) <= 120 THEN '61-120'
        WHEN (TRUNC(SYSDATE) - TRUNC(V.DTA_ENTRADA)) >  120 THEN '120+'
        ELSE 'NÃO CLASSIFICADO'
    END AS CLASSIFICAO_ESTOQUE,
    CASE
        WHEN (TRUNC(SYSDATE) - TRUNC(V.DTA_ENTRADA)) <= 60  THEN 1
        WHEN (TRUNC(SYSDATE) - TRUNC(V.DTA_ENTRADA)) <= 120 THEN 2
        WHEN (TRUNC(SYSDATE) - TRUNC(V.DTA_ENTRADA)) >  120 THEN 3
        ELSE 0
    END AS CLASSIFICAO_ID_ESTOQUE,
    -- ========== VALORES FINANCEIROS ==========
    V.VAL_COMPRA,
    V.VAL_CUSTO_CONTABIL,
    V.VAL_PRESENTE_VENDA,
    -- ========== CUSTO TAB+OPC+FT ==========
    COALESCE((
        CASE OFS.TIPO_PINTURA
            WHEN 'S' THEN COALESCE(VMP.PRECO_PUBLICO, VM.PRECO_PUBLICO, 0) + COALESCE(VMP.VAL_PINTURA_S, VM.VAL_PINTURA_S, 0)
            WHEN 'M' THEN COALESCE(VMP.PRECO_PUBLICO, VM.PRECO_PUBLICO, 0) + COALESCE(VMP.VAL_PINTURA_M, VM.VAL_PINTURA_M, 0)
            WHEN 'P' THEN COALESCE(VMP.PRECO_PUBLICO, VM.PRECO_PUBLICO, 0) + COALESCE(VMP.VAL_PINTURA_P, VM.VAL_PINTURA_P, 0)
            WHEN 'E' THEN COALESCE(VMP.PRECO_PUBLICO, VM.PRECO_PUBLICO, 0) + COALESCE(VMP.VAL_PINTURA_E, VM.VAL_PINTURA_E, 0)
            ELSE COALESCE(VMP.PRECO_PUBLICO, VM.PRECO_PUBLICO, 0)
        END
    ), 0)
    + COALESCE((
        SELECT SUM(COALESCE(OPC_V.VAL_OPCIONAL, OPC_E.VAL_OPCIONAL, OPC_M.VAL_OPCIONAL))
        FROM CNP.OFI_FICHA_OPCIONAL OPC_V
            INNER JOIN CNP.VEI_OPCIONAL_MODELO OPC_M
                ON OPC_M.EMPRESA = OPC_V.EMPRESA
               AND OPC_M.MODELO   = OPC_V.MODELO
               AND OPC_M.OPCIONAL = OPC_V.OPCIONAL
            LEFT JOIN CNP.VEI_OPCIONAL_MODELO_EDICAO OPC_E
                ON OPC_E.EMPRESA    = OPC_M.EMPRESA
               AND OPC_E.MODELO     = OPC_M.MODELO
               AND OPC_E.OPCIONAL   = OPC_M.OPCIONAL
               AND OPC_E.ANO_MODELO = OFS.ANO_MODELO
               AND OPC_E.EDICAO     = OFS.EDICAO
        WHERE OPC_V.EMPRESA = V.EMPRESA
          AND OPC_V.CHASSI  = V.CHASSI
    ), 0)
    + COALESCE((
        SELECT MC.VAL_FRETE_PF
        FROM CNP.FAT_MOVIMENTO_CAPA MC
            INNER JOIN CNP.FAT_MOVIMENTO_VEICULO MV
                ON MV.EMPRESA            = MC.EMPRESA
               AND MV.REVENDA            = MC.REVENDA
               AND MV.NUMERO_NOTA_FISCAL = MC.NUMERO_NOTA_FISCAL
               AND MV.SERIE_NOTA_FISCAL  = MC.SERIE_NOTA_FISCAL
               AND MV.TIPO_TRANSACAO     = MC.TIPO_TRANSACAO
               AND MV.CONTADOR          = MC.CONTADOR
        WHERE MC.EMPRESA              = V.EMPRESA_NFFRETE
          AND MC.REVENDA              = V.REVENDA_NFFRETE
          AND MC.NUMERO_NOTA_FISCAL   = V.NUMERO_NOTA_FISCAL_NFFRETE
          AND MC.SERIE_NOTA_FISCAL    = V.SERIE_NOTA_FISCAL_NFFRETE
          AND MC.TIPO_TRANSACAO       = V.TIPO_TRANSACAO_NFFRETE
          AND MC.CONTADOR             = V.CONTADOR_NFFRETE
          AND MC.MODALIDADE           = 'C'
          AND MC.STATUS              IN ('F', 'A')
          AND MV.VEICULO              = V.VEICULO
    ), 0) AS CUSTO_TAB_OPC_FT,
    -- ========== CUSTO TOTAL ==========
    COALESCE((
        SELECT SUM(VC2.VAL_PRESENTE)
        FROM CNP.VEI_VEICULO_CUSTEIO VC2,
             CNP.VEI_FORMULA_LINHA FL
        WHERE VC2.EMPRESA       = V.EMPRESA
          AND VC2.VEICULO       = V.VEICULO
          AND VC2.EMPRESA       = FL.EMPRESA
          AND VC2.FORMULA       = FL.FORMULA
          AND VC2.LINHA_FORMULA = FL.LINHA_FORMULA
          AND (FL.CUSTO_TOTAL = '+' OR (FL.TIPO = 'B' AND (FL.INCIDENCIA = '(' OR FL.INCIDENCIA = ')')))
          AND FL.STATUS = 'A'
        GROUP BY VC2.EMPRESA, VC2.VEICULO
    ), 0)
    -
    COALESCE((
        SELECT SUM(VC2.VAL_PRESENTE)
        FROM CNP.VEI_VEICULO_CUSTEIO VC2,
             CNP.VEI_FORMULA_LINHA FL
        WHERE VC2.EMPRESA       = V.EMPRESA
          AND VC2.VEICULO       = V.VEICULO
          AND VC2.EMPRESA       = FL.EMPRESA
          AND VC2.FORMULA       = FL.FORMULA
          AND VC2.LINHA_FORMULA = FL.LINHA_FORMULA
          AND FL.CUSTO_TOTAL    = '-'
          AND FL.STATUS         = 'A'
        GROUP BY VC2.EMPRESA, VC2.VEICULO
    ), 0)
    - COALESCE((
        SELECT SUM(VB.VAL_BONUS)
        FROM CNP.VEI_BONUS VB
        WHERE VB.EMPRESA           = V.EMPRESA
          AND VB.MODELO            = V.MODELO
          AND VB.DTA_COMPRA_INICIO IS NOT NULL
          AND TRUNC(V.DTA_ENTRADA) BETWEEN VB.DTA_COMPRA_INICIO  -- ✅ TRUNC no BETWEEN
                                       AND VB.DTA_COMPRA_FIM
          AND (VB.ANO_FABRICACAO IS NULL OR VB.ANO_FABRICACAO = OFS.ANO_FABRICACAO)
          AND (VB.ANO_MODELO     IS NULL OR VB.ANO_MODELO     = OFS.ANO_MODELO)
    ), 0) AS CUSTO_TOTAL,
    -- ========== DADOS COMPLEMENTARES DO VEÍCULO ==========
    OFS.PLACA,
    OFS.ANO_FABRICACAO,
    OFS.ANO_MODELO,
    OFS.RENAVAM,
    OFS.OBSERVACAO AS FIPE,
    VC.DES_COMBUSTIVEL AS COMBUSTIVEL,
    -- ========== CHAVE DE RELACIONAMENTO COM PAINEL VENDAS ==========
    VP.PROPOSTA

FROM CNP.VEI_VEICULO V
    INNER JOIN CNP.GER_REVENDA GR
        ON GR.EMPRESA = V.EMPRESA
       AND GR.REVENDA = V.REVENDA_ORIGEM
    LEFT JOIN CNP.VEI_MODELO VM
        ON VM.MODELO   = V.MODELO
       AND VM.EMPRESA  = V.EMPRESA
    LEFT JOIN CNP.VEI_MODELO_PRECO VMP
        ON VMP.EMPRESA = V.EMPRESA
       AND VMP.MODELO  = V.MODELO
       AND VMP.REVENDA = V.REVENDA_ORIGEM
    LEFT JOIN CNP.VEI_FAMILIA VF
        ON VF.FAMILIA  = VM.FAMILIA
       AND VF.EMPRESA  = VM.EMPRESA
    LEFT JOIN CNP.OFI_FICHA_SEGUIMENTO OFS
        ON OFS.EMPRESA = V.EMPRESA
       AND OFS.REVENDA = V.REVENDA_ORIGEM
       AND TRIM(OFS.CHASSI) = TRIM(V.CHASSI)
    LEFT JOIN CNP.VEI_COMBUSTIVEL VC
        ON VC.COMBUSTIVEL = OFS.COMBUSTIVEL
    LEFT JOIN CNP.VEI_SITUACAO VS
        ON VS.EMPRESA   = V.EMPRESA
       AND VS.SITUACAO  = V.SITUACAO
    LEFT JOIN (
        SELECT EMPRESA, REVENDA, VEICULO, MAX(PROPOSTA) AS PROPOSTA
        FROM CNP.VEI_PROPOSTA
        GROUP BY EMPRESA, REVENDA, VEICULO
    ) VP
        ON VP.EMPRESA  = V.EMPRESA
       AND VP.REVENDA  = V.REVENDA_ORIGEM
       AND VP.VEICULO  = V.VEICULO

WHERE 1=1
    AND V.SITUACAO IN ('ES', 'TM')
    AND V.DTA_ENTRADA >= ADD_MONTHS(TRUNC(SYSDATE), -60);